name: ml-alma-taccti
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas
  - fastapi
  - uvicorn
  - openpyxl
  - pydantic
  - scikit-learn
  - transformers
  - torch
  - xlrd
  - xlsxwriter
  - matplotlib
  - seaborn
  - jupyterlab
  - pip:
      - anyio
      - ace_tools